### ISSUE TITLE
update the setup with latest daysim

### ISSUE THREAD

**Issue by nsdhakar** [RSGInc/BKRCast#2] opened 2016-11-02 21:45 UTC
The latest DaySim, checked out on 10/28/2016, gets stuck in running choice models. Apparently it is running into an infinite loop in destination choice. The older DaySim, checked out on 08/12/2016, runs fine with the same inputs.

**Comment by PeterVermont** [comment] 2016-11-02 21:53
Other than reviewing the setting NProcessors as desired there is no special setup required. NBatches can be removed. If BKRCast uses the PSRC region specific code then it needs to set either PSRC=true or CustomizationDll=PSRC.dll (either one).

**Comment by nsdhakar** [comment] 2016-11-02 22:04
I have the BKR model running with the DaySim I checked out on 8/12/2016. Last Friday, I checked out a newer version and after updating some settings, tried to run it with the same skims and inputs. The newer DaySim reads in all the data but gets stuck while running choice models without throwing any error. I wonder what changed between the two version that caused it to get stuck?

![daysim_stuck](https://cloud.githubusercontent.com/assets/5324041/19949189/9598eabe-a10d-11e6-830d-f1716678c0e9.png)

**Comment by mabcal** [comment] 2016-11-02 22:09
That is strange, since none of the code changes have caused any changes to the outputs for any of the regions.

Just as a check, try changing the random seed and rerunning. It’s not a permanent fix, but maybe a temporary one, and will give us another clue.

We may need to try to run some past versions to isolate the problem.

Mark

**Comment by nsdhakar** [comment] 2016-11-02 23:05
It didn't work with different random seeds either. 

I tried the old daysim again and it ran without any problem. I will check all the skim matrices (I checked only one matrix in all skims), though it is strange that inputs work fine with the earlier version of daysim.

**Comment by bstabler** [comment] 2016-11-02 23:14
@PeterVermont - if you want to download the setup and debug it, then go ahead.  We have budget in the project for you to help.

**Comment by mabcal** [comment] 2016-11-02 23:26
That’s a good idea. I won’t have any time to help on this before tomorrow’s call.

This is usually caused by getting into an endless loop in DestinationSampler because it can’t find any destinations that can be reached from the current location.  We’ve put code in to fix it in the past, but it keeps finding new ways to get stuck because of bad input data.  I guess it could use some better diagnostic messages to break out of endless loops.  The destination sampling stuff was originally designed and written by John Bowman, and I’m not up on every detail of it.  What makes it complicated is that it can work at different spatial levels and there are some excluded alternatives, and it also has to work with the chosen alternative in estimation mode, so it’s pretty complex.  Maybe we want to create some simpler code that runs in application mode only.

**Comment by PeterVermont** [comment] 2016-11-03 13:37
Good!

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by PeterVermont** [comment] 2016-11-03 14:59
Mark is right on the money.

I can see the infinite looping


Line 432 in DestinationSampler.GetDestination is returning a null value and

SampleTourDestinations loops as long as it gets null:

                           // draw repeatedly until a sample item is drawn
                           do {
                                  sampleItem = GetDestination<TourSampleItem>(randomUniform01, _originParcel, _originSegmentZone, _excludedParcel, _excludedSegmentZone);
                                  if (sampleItem != null) {
                                         sampleItems[i] = sampleItem;
                                  }
                           } while (sampleItem == null);
                     }


I am not sure what the appropriate thing to do is….
……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by bstabler** [comment] 2016-11-03 15:08
Write out the relevant data, origin zone, impedances, etc so we can check the data for problems

**Comment by s-yan** [comment] 2016-11-03 15:28
Hi Ben,

Since we reserved some “dummy zones” for future zone splitting, could those zones be among the “guilty” ones? Anyway to accept the null values without dummying the dummies out?

Shuming

**Comment by mabcal** [comment] 2016-11-03 15:38
I think the best thing is to count the number of times this loop is executed without exiting, and after a few million times break with an error message that tells the tour origin parcel and zone IDs and tour destination purpose and any excluded parcel id, and the sampling segment.
That wont fix it, but will tell us where to look at the inputs.

The only recent change that seems like it might affect destination sampling is if the thread locks were removed from the random number generator. If so, maybe try running the last version before they were removed, or try putting them back in.

Sent from my Verizon Wireless 4G LTE DROID
On Nov 3, 2016 7:59 AM, Peter Andrews <notifications@github.com> wrote:
Mark is right on the money.

I can see the infinite looping


Line 432 in DestinationSampler.GetDestination is returning a null value and

SampleTourDestinations loops as long as it gets null:

// draw repeatedly until a sample item is drawn
do {
sampleItem = GetDestination<TourSampleItem>(randomUniform01, _originParcel, _originSegmentZone, _excludedParcel, _excludedSegmentZone);
if (sampleItem != null) {
sampleItems[i] = sampleItem;
}
} while (sampleItem == null);
}


I am not sure what the appropriate thing to do is….
……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by PeterVermont** [comment] 2016-11-03 15:40
I did not remove those thread locks

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by mabcal** [comment] 2016-11-03 15:43
Stefan also reported a problem in the parcel file where university enrollment is 0 for all parcels, which could cause issues in destination sampling, although I don't know why that would work with earlier code and not now.

Sent from my Verizon Wireless 4G LTE DROID
On Nov 3, 2016 7:59 AM, Peter Andrews <notifications@github.com> wrote:
Mark is right on the money.

I can see the infinite looping


Line 432 in DestinationSampler.GetDestination is returning a null value and

SampleTourDestinations loops as long as it gets null:

// draw repeatedly until a sample item is drawn
do {
sampleItem = GetDestination<TourSampleItem>(randomUniform01, _originParcel, _originSegmentZone, _excludedParcel, _excludedSegmentZone);
if (sampleItem != null) {
sampleItems[i] = sampleItem;
}
} while (sampleItem == null);
}


I am not sure what the appropriate thing to do is….
……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by mabcal** [comment] 2016-11-03 15:47
Then I really can't think of any recent code change that would give a new result or infinite loop with the exact same inputs and configuration settings.

Sent from my Verizon Wireless 4G LTE DROID
On Nov 3, 2016 8:40 AM, Peter Andrews <notifications@github.com> wrote:
I did not remove those thread locks

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by bstabler** [comment] 2016-11-03 16:50
@PeterVermont - please add code to count the number of times this loop is executed without exiting, and after a few million times break with an error message that tells the tour origin parcel and zone IDs and tour destination purpose and any excluded parcel id, and the sampling segment.  That wont fix it, but will tell us where to look at the inputs.

**Comment by PeterVermont** [comment] 2016-11-03 18:07
Prelim:

Message=GetDestination<TourSampleItem> returned null 1000000 times. _originParcel.ZoneId:31 _originParcel.ZoneKey: 32 _originSegmentZone.GetWeight: 26768.1350060919
       Source=DaySim.Framework

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by mabcal** [comment] 2016-11-03 18:34
It would also be useful to know what the value of “segment” was in the call to DestinationSampler, since that determines what _segmentZones is that has all the sampling probabilities
In SampleTourDestinations, it would be useful to know the IDs of _originParcel, and _excludedParcel.  We may need to break it while it’s in the loop and then step through the loop a few times to see what’s going on.



              public DestinationSampler(ChoiceProbabilityCalculator choiceProbabilityCalculator, int segment, int sampleSize, IParcel originParcel, IParcel chosenParcel) {
                     _choiceProbabilityCalculator = choiceProbabilityCalculator;
                     _segmentZones = Global.SegmentZones[segment];
                     _sampleSize = sampleSize;

                     _originParcel = originParcel;
                     _originSegmentZone = _segmentZones[originParcel.ZoneId];

                     if (chosenParcel != null) {
                           _chosenParcel = chosenParcel;
                           _chosenSegmentZone = _segmentZones[chosenParcel.ZoneId];
                     }

                     //JLB 20120329 removed these lines because usual work location model doesn't set a sampled dest to chosen when it is the residence location
                     //                   if (_choiceProbabilityCalculator.ModelIsInEstimationMode && chosenParcel == null) {
                     //                         throw new ChosenParcelNotSetInEstimationModeException();
                     //                   }
              }

              public int SampleTourDestinations(ISamplingUtilities samplingUtilities) {
                     var sampleItems = new TourSampleItem[_sampleSize];

                     for (var i = 0; i < _sampleSize; i++) {
                           TourSampleItem sampleItem;

                           var randomUniform01 = new RandomUniform01(samplingUtilities.SeedValues[i]);

                           // draw repeatedly until a sample item is drawn
                            do {
                                  sampleItem = GetDestination<TourSampleItem>(randomUniform01, _originParcel, _originSegmentZone, _excludedParcel, _excludedSegmentZone);
                                  if (sampleItem != null) {
                                         sampleItems[i] = sampleItem;
                                  }
                           } while (sampleItem == null);
                     }

**Comment by PeterVermont** [comment] 2016-11-03 18:56
GetDestination<TourSampleItem> returned null 20000000 times.
_originParcel.Id:41767
_originParcel.ZoneId:31
_originParcel.ZoneKey: 32

_originSegmentZone.Id: 31
_originSegmentZone.Key: 32
_originSegmentZone.TotalWeight: 26768.1350060919

_excludedParcel.Id:41768
_excludedParcel.ZoneId:31
_excludedParcel.ZoneKey: 32

_excludedSegmentZone.Id: 31
_excludedSegmentZone.Key: 32
_excludedSegmentZone.TotalWeight: 26768.1350060919

I haven’t learned the code but is the issue that the originSegment and the excludedSegment are the same?

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by mabcal** [comment] 2016-11-03 19:07
ZoneKey is the relevant one to print. (ZoneID is internal to DaySim)

It’s ok if the origin zone and excluded zone are the same, as long as there are other zones with positive weights that can be reached on the network, or other parcels within that same zone with positive weights.

Since the land use variables that were used in the relevant sampling weight calculations are based on “segment” in the call to DestinationSampler, it would be very useful to know that.

Nagendra – is zone 32 connected to other zones in the auto networks?

Mark

**Comment by nsdhakar** [comment] 2016-11-03 19:12
@PeterVermont: can you please add tour purpose also?
@mabcal: what is _excludedParcel, how is it determined? is it related to destination eligible taz? doesn't look  that way though.
yes, zone 32 is connected and it has valid travel times in skims (checked one time period)

**Comment by bstabler** [comment] 2016-11-03 19:24
please add time period as well to the print out

**Comment by mabcal** [comment] 2016-11-03 19:28
I think that one is not accessible in DestinationSampler, because the sampling weights are not time-period specific, so it’s not passed – really the only tour information that is passed is the sampling segment (based on tour purpose and type and person type) the origin parcel, and the chosen destination parcel (in estimation mode only)

**Comment by mabcal** [comment] 2016-11-03 19:38
Tour purpose is not accessible there -  sampling “segment” will be best, as I mentioned in my last few e-mails.

Excluded is one that is not allowed to be sampled because it is already used as a special alternative – an example is the usual work parcel in the work tour destination model.

Mark

**Comment by bstabler** [comment] 2016-11-03 19:54
It would also be helpful to decode the sampling segment value (based on tour purpose and type and person type) and print the tour purpose and type and person type

**Comment by PeterVermont** [comment] 2016-11-03 20:14
{Tour ID: 13220651, Person Day ID: 1322065, Person ID: 1322065
Household ID: 738000, Person Sequence: 1, Day: 1, Sequence: 1, Parent Tour Sequence: 0
Destination Parcel ID: 0, Destination Zone Key: 0, Destination Address Type: 0, Destination Purpose: 1, Mode: 0, Destination Arrival Time: 300, Destination Departure Time: 840
}

……………………………………………..
PETER ANDREWS
Senior Software Engineer

RSG
55 Railroad Row | White River Junction, VT 05001
o 802.359.6411 | m 802.356.3141
www.rsginc.com<http://www.rsginc.com/>
……………………………………………..

**Comment by mabcal** [comment] 2016-11-03 21:01
This is a work tour. Tour destination and mode haven’t been predicted yet at this point.

Note that the sampling weights are pre-calculated before the run, and use the auto SOV in-vehicle time skim for 6 AM, regardless of the time of day of the actual tour.  (The sampling weights are only supposed to be approximately like model probabilities, and we don’t want to use all the RAM to store different sets for different times of day)

Based on the previous info Peter sent, this person has a usual work parcel (41768) in the same zone (32) as the residence parcel (41767).

If zone 32 is actually connected to other zones and other zones have employment, I can’t see how the code can get into an infinite loop.  I guess I may need to check out the data and try debugging it by stepping through the code.



By the way – have we ever seen in profiling how much time is spent in DestinationSampler.GetDestination ?   It seems like that code could be made a lot more efficient by doing a binary search on the weight array rather than sequential.

**Comment by mabcal** [comment] 2016-11-03 23:19
Problem solved – needed to add the config line for PSRC below to get it to read in the HDF5 skim files correctly.

HDF5SkimScaledAndCondensed = true

**Closed** 2016-11-03 23:40 UTC
Labels: help wanted
